# This is a config for E2B sandbox template.
# You can use template ID (lghea2bdih4aaeryhsor) or template name (nextjs15-v1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("nextjs15-v1") # Sync sandbox
# sandbox = await AsyncSandbox.create("nextjs15-v1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nextjs15-v1')

team_id = "1f8a223f-8fe4-495e-8c39-915b74aaf4a8"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nextjs15-v1"
template_id = "lghea2bdih4aaeryhsor"
