'use client'

import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { Input } from '@/components/ui/input'
import { ScrollArea } from '@/components/ui/scroll-area'
import { IconName } from '@/types/icon-name'
import {
  Search,
  Check,
  Home,
  User,
  Settings,
  Mail,
  Phone,
  Calendar,
  FileText,
  Image,
  Video,
  Music,
  Download,
  Upload,
  Edit,
  Trash2,
  Heart,
  Star,
  Bookmark,
  Share,
  Copy,
  ScissorsIcon as Cut,
  ClipboardPasteIcon as Paste,
  Save,
  Folder,
  File,
  Archive,
  Database,
  Server,
  Globe,
  Wifi,
  Bluetooth,
  Battery,
  Volume2,
  Camera,
  Printer,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Watch,
  Gamepad2,
  Car,
  Plane,
  Ship,
  Bike,
  Bus,
  Train,
  Truck,
  MapPin,
  Navigation,
  Compass,
  Map,
  Clock,
  Timer,
  TimerIcon as Stopwatch,
  AlarmClock,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Zap,
  Flame,
  Snowflake,
  Umbrella,
  Shield,
  Lock,
  Unlock,
  Key,
  Eye,
  EyeOff,
  Bell,
  BellOff,
  MessageCircle,
  MessageSquare,
  Send,
  Inbox,
  InboxIcon as Outbox,
  Tag,
  Flag,
  Award,
  Trophy,
  Medal,
  Gift,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  DollarSign,
  PiggyBank,
  Wallet,
  Calculator,
  TrendingUp,
  TrendingDown,
  BarChart,
  PieChart,
  Activity,
  Target,
  Crosshair,
  Focus,
  Maximize,
  Minimize,
  RotateCcw,
  RotateCw,
  RefreshCw,
  Power,
  PlayCircle,
  PauseCircle,
  StopCircle,
  SkipBack,
  SkipForward,
  FastForward,
  Rewind,
  Repeat,
  Shuffle,
  VolumeX,
  Volume1,
  Mic,
  MicOff,
  Headphones,
  Radio,
  Tv,
  Film,
  Clapperboard,
  Palette,
  Brush,
  Scissors,
  Ruler,
  Wrench,
  Hammer,
  WrenchIcon as Screwdriver,
  Drill,
  Pickaxe,
  Shovel,
  Building,
  Building2,
  Factory,
  Warehouse,
  Store,
  School,
  GraduationCap,
  BookOpen,
  Book,
  Library,
  Newspaper,
  Coffee,
  Pizza,
  Apple,
  Banana,
  Cherry,
  Grape,
  Carrot,
  Fish,
  Beef,
  Egg,
  Milk,
  CroissantIcon as Bread,
  Cookie,
  IceCream,
  Wine,
  Beer,
  Martini,
  Utensils,
  ChefHat,
  Shirt,
  Crown,
  Glasses,
  Briefcase,
  Backpack,
  Luggage,
  Tent,
  TreePine,
  Mountain,
  Waves,
  Flower,
  Leaf,
  Bug,
  Bird,
  Cat,
  Dog,
  Rabbit,
  Turtle,
  FlowerIcon as Butterfly,
  Snail,
  Footprints,
  PawPrintIcon as Paw,
  Bone,
  Stethoscope,
  Pill,
  Syringe,
  LigatureIcon as Bandage,
  Thermometer,
  Microscope,
  TestTube,
  Dna,
  Atom,
  Magnet,
  Lightbulb,
  Flashlight,
  CandlestickChartIcon as Candle,
  Lamp,
  LampIcon as Lantern,
  StickyNote,
} from 'lucide-react'
import { useState } from 'react'

export const availableIcons = [
  { name: IconName.Home, icon: Home },
  { name: IconName.User, icon: User },
  { name: IconName.Settings, icon: Settings },
  { name: IconName.Mail, icon: Mail },
  { name: IconName.Phone, icon: Phone },
  { name: IconName.Calendar, icon: Calendar },
  { name: IconName.FileText, icon: FileText },
  { name: IconName.Image, icon: Image },
  { name: IconName.Video, icon: Video },
  { name: IconName.Music, icon: Music },
  { name: IconName.Download, icon: Download },
  { name: IconName.Upload, icon: Upload },
  { name: IconName.Edit, icon: Edit },
  { name: IconName.Trash, icon: Trash2 },
  { name: IconName.Heart, icon: Heart },
  { name: IconName.Star, icon: Star },
  { name: IconName.Bookmark, icon: Bookmark },
  { name: IconName.Share, icon: Share },
  { name: IconName.Copy, icon: Copy },
  { name: IconName.Cut, icon: Cut },
  { name: IconName.Paste, icon: Paste },
  { name: IconName.Save, icon: Save },
  { name: IconName.Folder, icon: Folder },
  { name: IconName.File, icon: File },
  { name: IconName.Archive, icon: Archive },
  { name: IconName.Database, icon: Database },
  { name: IconName.Server, icon: Server },
  { name: IconName.Globe, icon: Globe },
  { name: IconName.Wifi, icon: Wifi },
  { name: IconName.Bluetooth, icon: Bluetooth },
  { name: IconName.Battery, icon: Battery },
  { name: IconName.Volume, icon: Volume2 },
  { name: IconName.Camera, icon: Camera },
  { name: IconName.Printer, icon: Printer },
  { name: IconName.Monitor, icon: Monitor },
  { name: IconName.Smartphone, icon: Smartphone },
  { name: IconName.Tablet, icon: Tablet },
  { name: IconName.Laptop, icon: Laptop },
  { name: IconName.Watch, icon: Watch },
  { name: IconName.Gamepad, icon: Gamepad2 },
  { name: IconName.Car, icon: Car },
  { name: IconName.Plane, icon: Plane },
  { name: IconName.Ship, icon: Ship },
  { name: IconName.Bike, icon: Bike },
  { name: IconName.Bus, icon: Bus },
  { name: IconName.Train, icon: Train },
  { name: IconName.Truck, icon: Truck },
  { name: IconName.MapPin, icon: MapPin },
  { name: IconName.Navigation, icon: Navigation },
  { name: IconName.Compass, icon: Compass },
  { name: IconName.Map, icon: Map },
  { name: IconName.Clock, icon: Clock },
  { name: IconName.Timer, icon: Timer },
  { name: IconName.Stopwatch, icon: Stopwatch },
  { name: IconName.AlarmClock, icon: AlarmClock },
  { name: IconName.Sun, icon: Sun },
  { name: IconName.Moon, icon: Moon },
  { name: IconName.Cloud, icon: Cloud },
  { name: IconName.CloudRain, icon: CloudRain },
  { name: IconName.Zap, icon: Zap },
  { name: IconName.Flame, icon: Flame },
  { name: IconName.Snowflake, icon: Snowflake },
  { name: IconName.Umbrella, icon: Umbrella },
  { name: IconName.Shield, icon: Shield },
  { name: IconName.Lock, icon: Lock },
  { name: IconName.Unlock, icon: Unlock },
  { name: IconName.Key, icon: Key },
  { name: IconName.Eye, icon: Eye },
  { name: IconName.EyeOff, icon: EyeOff },
  { name: IconName.Bell, icon: Bell },
  { name: IconName.BellOff, icon: BellOff },
  { name: IconName.MessageCircle, icon: MessageCircle },
  { name: IconName.MessageSquare, icon: MessageSquare },
  { name: IconName.Send, icon: Send },
  { name: IconName.Inbox, icon: Inbox },
  { name: IconName.Outbox, icon: Outbox },
  { name: IconName.Tag, icon: Tag },
  { name: IconName.Flag, icon: Flag },
  { name: IconName.Award, icon: Award },
  { name: IconName.Trophy, icon: Trophy },
  { name: IconName.Medal, icon: Medal },
  { name: IconName.Gift, icon: Gift },
  { name: IconName.ShoppingCart, icon: ShoppingCart },
  { name: IconName.ShoppingBag, icon: ShoppingBag },
  { name: IconName.CreditCard, icon: CreditCard },
  { name: IconName.DollarSign, icon: DollarSign },
  { name: IconName.PiggyBank, icon: PiggyBank },
  { name: IconName.Wallet, icon: Wallet },
  { name: IconName.Calculator, icon: Calculator },
  { name: IconName.TrendingUp, icon: TrendingUp },
  { name: IconName.TrendingDown, icon: TrendingDown },
  { name: IconName.BarChart, icon: BarChart },
  { name: IconName.PieChart, icon: PieChart },
  { name: IconName.Activity, icon: Activity },
  { name: IconName.Target, icon: Target },
  { name: IconName.Crosshair, icon: Crosshair },
  { name: IconName.Focus, icon: Focus },
  { name: IconName.Maximize, icon: Maximize },
  { name: IconName.Minimize, icon: Minimize },
  { name: IconName.RotateCcw, icon: RotateCcw },
  { name: IconName.RotateCw, icon: RotateCw },
  { name: IconName.RefreshCw, icon: RefreshCw },
  { name: IconName.Power, icon: Power },
  { name: IconName.PlayCircle, icon: PlayCircle },
  { name: IconName.PauseCircle, icon: PauseCircle },
  { name: IconName.StopCircle, icon: StopCircle },
  { name: IconName.SkipBack, icon: SkipBack },
  { name: IconName.SkipForward, icon: SkipForward },
  { name: IconName.FastForward, icon: FastForward },
  { name: IconName.Rewind, icon: Rewind },
  { name: IconName.Repeat, icon: Repeat },
  { name: IconName.Shuffle, icon: Shuffle },
  { name: IconName.VolumeX, icon: VolumeX },
  { name: IconName.Volume1, icon: Volume1 },
  { name: IconName.Mic, icon: Mic },
  { name: IconName.MicOff, icon: MicOff },
  { name: IconName.Headphones, icon: Headphones },
  { name: IconName.Radio, icon: Radio },
  { name: IconName.Tv, icon: Tv },
  { name: IconName.Film, icon: Film },
  { name: IconName.Clapperboard, icon: Clapperboard },
  { name: IconName.Palette, icon: Palette },
  { name: IconName.Brush, icon: Brush },
  { name: IconName.Scissors, icon: Scissors },
  { name: IconName.Ruler, icon: Ruler },
  { name: IconName.Wrench, icon: Wrench },
  { name: IconName.Hammer, icon: Hammer },
  { name: IconName.Screwdriver, icon: Screwdriver },
  { name: IconName.Drill, icon: Drill },
  { name: IconName.Pickaxe, icon: Pickaxe },
  { name: IconName.Shovel, icon: Shovel },
  { name: IconName.Building, icon: Building },
  { name: IconName.Building2, icon: Building2 },
  { name: IconName.Factory, icon: Factory },
  { name: IconName.Warehouse, icon: Warehouse },
  { name: IconName.Store, icon: Store },
  { name: IconName.School, icon: School },
  { name: IconName.GraduationCap, icon: GraduationCap },
  { name: IconName.BookOpen, icon: BookOpen },
  { name: IconName.Book, icon: Book },
  { name: IconName.Library, icon: Library },
  { name: IconName.Newspaper, icon: Newspaper },
  { name: IconName.Coffee, icon: Coffee },
  { name: IconName.Pizza, icon: Pizza },
  { name: IconName.Apple, icon: Apple },
  { name: IconName.Banana, icon: Banana },
  { name: IconName.Cherry, icon: Cherry },
  { name: IconName.Grape, icon: Grape },
  { name: IconName.Carrot, icon: Carrot },
  { name: IconName.Fish, icon: Fish },
  { name: IconName.Beef, icon: Beef },
  { name: IconName.Egg, icon: Egg },
  { name: IconName.Milk, icon: Milk },
  { name: IconName.Bread, icon: Bread },
  { name: IconName.Cookie, icon: Cookie },
  { name: IconName.IceCream, icon: IceCream },
  { name: IconName.Wine, icon: Wine },
  { name: IconName.Beer, icon: Beer },
  { name: IconName.Martini, icon: Martini },
  { name: IconName.Utensils, icon: Utensils },
  { name: IconName.ChefHat, icon: ChefHat },
  { name: IconName.Shirt, icon: Shirt },
  { name: IconName.Crown, icon: Crown },
  { name: IconName.Glasses, icon: Glasses },
  { name: IconName.Briefcase, icon: Briefcase },
  { name: IconName.Backpack, icon: Backpack },
  { name: IconName.Luggage, icon: Luggage },
  { name: IconName.Tent, icon: Tent },
  { name: IconName.TreePine, icon: TreePine },
  { name: IconName.Mountain, icon: Mountain },
  { name: IconName.Waves, icon: Waves },
  { name: IconName.Flower, icon: Flower },
  { name: IconName.Leaf, icon: Leaf },
  { name: IconName.Bug, icon: Bug },
  { name: IconName.Bird, icon: Bird },
  { name: IconName.Cat, icon: Cat },
  { name: IconName.Dog, icon: Dog },
  { name: IconName.Rabbit, icon: Rabbit },
  { name: IconName.Turtle, icon: Turtle },
  { name: IconName.Butterfly, icon: Butterfly },
  { name: IconName.Snail, icon: Snail },
  { name: IconName.Footprints, icon: Footprints },
  { name: IconName.Paw, icon: Paw },
  { name: IconName.Bone, icon: Bone },
  { name: IconName.Stethoscope, icon: Stethoscope },
  { name: IconName.Pill, icon: Pill },
  { name: IconName.Syringe, icon: Syringe },
  { name: IconName.Bandage, icon: Bandage },
  { name: IconName.Thermometer, icon: Thermometer },
  { name: IconName.Microscope, icon: Microscope },
  { name: IconName.TestTube, icon: TestTube },
  { name: IconName.DNA, icon: Dna },
  { name: IconName.Atom, icon: Atom },
  { name: IconName.Magnet, icon: Magnet },
  { name: IconName.Lightbulb, icon: Lightbulb },
  { name: IconName.Flashlight, icon: Flashlight },
  { name: IconName.Candle, icon: Candle },
  { name: IconName.Lamp, icon: Lamp },
  { name: IconName.Lantern, icon: Lantern },
  { name: IconName.StickyNote, icon: StickyNote },
]
interface IconSelectorProps {
  selectedIcon: string
  toolId: string
  onIconChange: (iconName: string, toolId: string) => void
}

export default function IconSelector({
  selectedIcon = 'Home',
  toolId,
  onIconChange,
}: IconSelectorProps) {
  const [searchTerm, setSearchTerm] = useState('')
  const [isOpen, setIsOpen] = useState(false)

  // Filter icons based on search term
  const filteredIcons = availableIcons.filter((icon) =>
    icon.name.toLowerCase().includes(searchTerm.toLowerCase()),
  )

  // Find the currently selected icon
  const currentIcon = availableIcons.find((icon) => icon.name === selectedIcon)
  const CurrentIconComponent = currentIcon?.icon || Home

  const handleIconSelect = (iconName: string) => {
    onIconChange(iconName, toolId)
    setIsOpen(false)
    setSearchTerm('')
  }

  return (
    <DropdownMenu open={isOpen} onOpenChange={setIsOpen}>
      <DropdownMenuTrigger asChild>
        <CurrentIconComponent className="h-4 w-4" />
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-80 p-0" align="start">
        <div className="p-3 border-b">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Filter icons..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-9"
            />
          </div>
        </div>
        <ScrollArea className="h-80">
          <div className="p-2">
            <div className="grid grid-cols-8 gap-1">
              {filteredIcons.map((icon) => {
                const IconComponent = icon.icon
                const isSelected = icon.name === selectedIcon

                return (
                  <Button
                    key={icon.name}
                    variant="ghost"
                    size="sm"
                    className={`h-10 w-10 p-0 relative ${
                      isSelected
                        ? 'bg-primary text-primary-foreground'
                        : 'hover:bg-muted'
                    }`}
                    onClick={() => handleIconSelect(icon.name)}
                    title={icon.name}
                  >
                    <IconComponent className="h-4 w-4" />
                    {isSelected && (
                      <Check className="absolute -top-1 -right-1 h-3 w-3 bg-primary text-primary-foreground rounded-full p-0.5" />
                    )}
                  </Button>
                )
              })}
            </div>
            {filteredIcons.length === 0 && (
              <div className="text-center py-8 text-muted-foreground">
                No icons found matching &quot;{searchTerm}&quot;
              </div>
            )}
          </div>
        </ScrollArea>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
